import pandas as pd

configfile: "config/config.yaml"

metadata = pd.read_csv(config["metadata_file"], comment="#")
metadata_query = "Nf == {Nf} and Nt == {Nt} and Nx == {Nx} and Ny == {Ny} and Nz == {Nz} and mf == {mf}"
subdir_format = "nf{Nf}/mf{mf}/{Nx}x{Ny}x{Nz}x{Nt}"

def get_metadata(column, from_df=metadata):
    def get_metadata_inner(wildcards):
        return lookup(within=from_df, query=metadata_query.format(**wildcards), cols=column)

    return get_metadata_inner

include: "rules/za.smk"
include: "rules/vp-momentum.smk"
include: "rules/time-moment.smk"
include: "rules/comparison.smk"


vp_momentum_plots = [
    "Z_A_eff",
    "Z_A_fit",
    "vpf_light_ensembles",
    "vpf_heavy_ensembles",
    "S_parameter_mf",
    "vpf_Nf8_mf0.015_42x42x42x56",
    "renormalised_vpf_Nf8_mf0.015_42x42x42x56",
]
time_moment_plots = [
    "zero_momentum_correlator_Nf8_mf0.009_48x48x48x64",
]
comparison_plots = [
    "S_tm_vp_comparison",
    "rho_mass_comparison",
]
tables = [
    "S_parameter",
]

rule all:
    input:
        plots=expand(
            "assets/plots/{plot_name}.pdf", plot_name=(
                vp_momentum_plots + time_moment_plots + comparison_plots
            ),
        ),
        tables=expand("assets/tables/{table_name}.tex", table_name=tables),
    default_target: True


rule copy_ensemble_plot:
    input:
        f"processed_data/{subdir_format}/{{filename}}.{{extension}}",
    output:
        "assets/plots/{filename}_Nf{Nf}_mf{mf}_{Nx}x{Ny}x{Nz}x{Nt}.{extension}",
    shell:
        "cp {input} {output}"
