import pandas as pd

configfile: "config/config.yaml"

metadata = pd.read_csv(config["metadata_file"], comment="#")
metadata_query = "Nf == {Nf} and Nt == {Nt} and Nx == {Nx} and Ny == {Ny} and Nz == {Nz} and mf == {mf}"
subdir_format = "nf{Nf}/mf{mf}/{Nx}x{Ny}x{Nz}x{Nt}"

def get_metadata(column, from_df=metadata):
    def get_metadata_inner(wildcards):
        return lookup(within=from_df, query=metadata_query.format(**wildcards), cols=column)

    return get_metadata_inner

include: "rules/meta.smk"
include: "rules/za.smk"
include: "rules/vp-momentum.smk"
include: "rules/v-a-correlator.smk"
include: "rules/time-moment.smk"
include: "rules/comparison.smk"


vp_momentum_plots = [
    "Z_A_eff",
    "Z_A_fit",
    "vpf_light_ensembles",
    "vpf_heavy_ensembles",
    "S_parameter_mf",
    "S_parameter_mf_fit_range_small",
    "S_parameter_mf_fit_range_large",
    "S_parameter_chisquare_mf_fit_range_small",
    "S_parameter_chisquare_mf_fit_range_large",
    "vpf_Nf8_mf0.015_42x42x42x56",
    "renormalised_vpf_Nf8_mf0.015_42x42x42x56",
]
time_moment_plots = [
    "zero_momentum_correlator_Nf8_mf0.009_48x48x48x64",
    "finite_volume_fit",
    "S_timemoment_contributions",
    "fitted_zero_momentum_correlator_Nf8_mf0.009_48x48x48x64",
    "S_extrapolation_Nf8_mf0.009_48x48x48x64",
]
comparison_plots = [
    "S_tm_vp_comparison",
    "rho_mass_comparison",
    "a_1_over_rho_mass_comparison",
    "rho_over_a_1_decay_comparison",
    "rho_over_pi_decay_comparison",
    "ksrf_i_ii",
    "ksrf_ii_lsd",
    "wsr_i",
    "wsr_ii",
    "S_parameter_mpi_L_group_by_mass",
    "S_parameter_mpi_L_group_by_length",
    "S_parameter_infinite_volume_comparison",
    "S_parameter_infinite_volume_comparison_lsd",
    "l10_r",
]
meta_plots = ["pv_spectrum"]
tables = [
    "S_parameter",
    "sum_rules",
    "spectrum",
    "dmo_l10_r",
    "ensembles",
    "quoted_spectrum",
]
definitions = [
    "Z_A_eff_ensembles",
    "Z_A",
    "pade_chisquare",
    "lightest_pade_result",
    "vpf_light_ensembles",
    "vpf_heavy_ensembles",
    "lightest_tm_fit_result",
    "ensemble_groups",
    "infinite_volume_time_moment",
    "lattice_spacing_matching",
    "lightest_l10_r",
    "spectrum_observations",
    "lightest_infinite_volume_S_tm",
]
data_assets = ["ensemble_data.csv", "Z_A.json"]

rule all:
    input:
        plots=expand(
            "assets/plots/{plot_name}.pdf", plot_name=(
                vp_momentum_plots + time_moment_plots + comparison_plots + meta_plots
            ),
        ),
        tables=expand("assets/tables/{table_name}.tex", table_name=tables),
        definitions="assets/definitions/all_definitions.tex",
        data=expand("data_assets/{filename}", filename=data_assets),
    default_target: True


rule all_definitions:
    params:
        content="|".join([f"\\input {{assets/definitions/{filename}}}" for filename in definitions])
    input:
        expand("assets/definitions/{filename}.tex", filename=definitions),
    output:
        "assets/definitions/all_definitions.tex",
    shell:
        r"echo '{params.content}' | tr '|' '\n' > {output}"


rule copy_ensemble_plot:
    input:
        f"processed_data/{subdir_format}/{{filename}}.{{extension}}",
    output:
        "assets/plots/{filename}_Nf{Nf}_mf{mf}_{Nx}x{Ny}x{Nz}x{Nt}.{extension}",
    shell:
        "cp {input} {output}"


rule copy_lightest_definition:
    input:
        "processed_data/nf8/mf0.009/48x48x48x64/{filename}.tex",
    output:
        "assets/definitions/lightest_{filename}.tex",
    shell:
        "cp {input} {output}"


rule copy_lightest_definition_infinite_volume:
    input:
        "processed_data/nf8/mf0.009/{filename}.tex",
    output:
        "assets/definitions/lightest_{filename}.tex",
    shell:
        "cp {input} {output}"


rule ensemble_csv:
    params:
        module=lambda wildcards, input: input.script.replace("/", ".")[:-3],
    input:
        previous_data="previous_data/spectrum.csv",
        data=[
            rule.output.data.format(**row, kind="renormalised")
            for rule in [rules.S_parameter_tm_fit, rules.pade_fit_systematics, rules.compute_sum_rules, rules.Z_A]
            for row in metadata.to_dict(orient="records")
        ],
        spectrum_data=[
            rules.meson_v_a.output.data.format(**row, channel=channel)
            for row in metadata.to_dict(orient="records")
            for channel in ["V", "A"]
        ],
        time_moment_infinite_volume=[
            rules.infinite_volume_extrapolate.output.data.format(**ensemble)
            for ensemble in metadata.query(
                "plot_large_volume_light_ensembles"
            ).to_dict(orient="records")
        ],
        script="s_parameter/data/export_ensemble_data.py",
    output:
        data="data_assets/ensemble_data.csv",
    conda:
        "envs/python.yml"
    shell:
        "python -m {params.module} {input.previous_data}"
        " {input.data} {input.spectrum_data} {input.time_moment_infinite_volume}"
        " --output_file {output.data}"
